create or replace 
trigger LAST_SESSION 
AFTER LOGON ON DATABASE 
BEGIN
  UPDATE ESTADISTICAS SET ULTIMA_SESION = CURRENT_TIMESTAMP,NUMERO_CONEXIONES = NUMERO_CONEXIONES+1 WHERE USUARIO = USER;
  
    if sql%notfound then 
    insert into estadisticas(USUARIO,ULTIMA_SESION,NUMERO_CONEXIONES,TIEMPO_EMPLEADO) VALUES(USER,CURRENT_TIMESTAMP,1,0);
    end if;
END;
